### ISSUE TITLE
Odd snapgene parses

### ISSUE THREAD

**Issue by mcltd** [DeskGen/dgparse#30]
Deleted, moved to #3815

**Comment by mcltd** [comment]
On Mon, Dec 21, 2015 at 11:33 AM, Joseph Wolanski <josephw@desktopgenetics.com> wrote:

    1. c0014.dna -  NO FEATURES IN SNAPGENE
    2. PAL3/c0081 PAL3 from Photorhabdus luminescens.dna - NO FEATURES IN SNAPGENE
    3. EB0138 pML21.dna - NO FEATURES IN SNAPGENE

    4. c0052 bleoR/c0052 BleoR Zeocin in pBRIDT +.dna - PLASMID STRUCTURE IN SNAPGENE

    5. EB0308 NLS_DdrB_pTEF1_cycT.dna - CONSTRUCT STRUCTURE IN SNAPGENE
    6. EB0398 FNRv-GFP reporter in pUC57 Kan.dna - CONSTRUCT STRUCTURE IN SNAPGENE

**Comment by mcltd** [comment]
Further investigation of EB0138 indicates that a protein sequence was parsed:
```
DACCVDBKSBACTRATTHTITRRATTHTITTSINGTHRCTITINRATTHTITCNCBIRCSGCDSCAIAVKMGCDSCNDKKKKWATVKGCDSNGCDSCKSISNYGCDSNDKAIAITAKC
```

**Comment by mcltd** [comment]
Is this an error in the input file or in the snapgene parser?

**Comment by mcltd** [comment]
@JoeWolanski FYI

**Comment by JoeWolanski** [comment]
:+1:
